name: nespreso_host
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - fastapi
  - netcdf4
  - numpy
  - matplotlib
  - pandas
  - pydantic
  - scipy
  - pytorch
  - torchvision
  - tqdm
  - xarray
  - cmocean
  - cartopy
  - gsw
  - httpx
  - mat73
  - scikit-learn
  - seaborn
  - ipykernel
  - flask
  - rasterio
  - pip
  - pip:
      - torch
      - light-the-torch